-- MySQL Script generated by MySQL Workbench
-- Sat 03 Jan 2015 16:17:58 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zey
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zey` ;

-- -----------------------------------------------------
-- Schema zey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zey` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zey` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `userID` BIGINT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NULL,
  `UUID` VARCHAR(36) NOT NULL,
  `LastLogin` TIMESTAMP NULL,
  `DateCreated` TIMESTAMP NULL,
  `_dateModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conversation` ;

CREATE TABLE IF NOT EXISTS `conversation` (
  `conversationID` BIGINT NOT NULL AUTO_INCREMENT,
  `user1ID` BIGINT NOT NULL,
  `user2ID` BIGINT NOT NULL,
  `Date1Read` TIMESTAMP NULL,
  `Date2Read` TIMESTAMP NULL,
  `DateCreated` TIMESTAMP NULL,
  `_dateModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`conversationID`),
  INDEX `fk_conversation_user_idx` (`user1ID` ASC),
  INDEX `fk_conversation_user2_idx` (`user2ID` ASC),
  CONSTRAINT `fk_conversation_user1`
    FOREIGN KEY (`user1ID`)
    REFERENCES `user` (`userID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_user2`
    FOREIGN KEY (`user2ID`)
    REFERENCES `user` (`userID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message` ;

CREATE TABLE IF NOT EXISTS `message` (
  `messageID` BIGINT NOT NULL AUTO_INCREMENT,
  `conversationID` BIGINT NOT NULL,
  `Content` TEXT NULL,
  `DateCreated` TIMESTAMP NULL,
  `_dateModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`messageID`),
  INDEX `fk_message_conversation_idx` (`conversationID` ASC),
  CONSTRAINT `fk_message_conversation`
    FOREIGN KEY (`conversationID`)
    REFERENCES `conversation` (`conversationID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
